"""Train a scikit-learn classifier on collected hand landmark data.

Usage:
    python train_model.py

This script expects a `data.csv` file generated by `collect_data.py`.
It outputs `model.pkl`.
"""

import csv
import pathlib
import sys

try:
    import joblib
    import numpy as np
    from sklearn.ensemble import RandomForestClassifier
    from sklearn.model_selection import train_test_split
    from sklearn.pipeline import Pipeline
    from sklearn.preprocessing import StandardScaler
except ModuleNotFoundError as e:
    print(f"ERROR: Missing dependency: {e.name}")
    print("Install required packages with: python -m pip install -r requirements.txt")
    sys.exit(1)


DATA_PATH = pathlib.Path(__file__).resolve().parent / "data.csv"
MODEL_PATH = pathlib.Path(__file__).resolve().parent / "model.pkl"


def create_dummy_data(path: pathlib.Path, n_samples_per_label: int = 10):
    """Create a small synthetic dataset so the project can run without manual data collection."""
    print("data.csv not found. Creating a small dummy dataset for demo purposes.")
    labels = ["A", "B"]
    with path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow(["label"] + [f"f{i}" for i in range(21 * 3)])
        rng = np.random.default_rng(42)
        for label in labels:
            for _ in range(n_samples_per_label):
                row = [label] + rng.random(21 * 3).tolist()
                writer.writerow(row)


def load_data(path: pathlib.Path):
    if not path.exists() or path.stat().st_size == 0:
        create_dummy_data(path)

    data = np.genfromtxt(str(path), delimiter=",", dtype=str)
    if data.size == 0:
        # If the file exists but is empty or malformed, regenerate it.
        create_dummy_data(path)
        data = np.genfromtxt(str(path), delimiter=",", dtype=str)
    if data.size == 0:
        raise ValueError("No data found in data.csv")

    # First row is header.
    header = data[0]
    values = data[1:]

    X = values[:, 1:].astype(float)
    y = values[:, 0]
    return X, y


def main():
    X, y = load_data(DATA_PATH)

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42, stratify=y
    )

    pipeline = Pipeline(
        [
            ("scaler", StandardScaler()),
            ("clf", RandomForestClassifier(n_estimators=200, random_state=42)),
        ]
    )

    pipeline.fit(X_train, y_train)
    acc = pipeline.score(X_test, y_test)

    joblib.dump(pipeline, MODEL_PATH)

    print(f"Trained model saved to {MODEL_PATH}")
    print(f"Test accuracy: {acc:.3f}")


if __name__ == "__main__":
    sys.exit(main())
